spring:
  application:
    name: Library
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: password
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    path: "/swagger-ui/index.html"