apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  type: NodePort
  selector:
    app: library-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080